version: '3.2'
services:
  mongo:
    image: mongo:4.2.5
    volumes:
      - type: volume
        source: mongo
        target: /data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongs123

volumes:
  mongo:
