version: '3.2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mongs123
      TZ: Asia/Shanghai

volumes:
  mysql: 
