version: '3.2'
services:
  redis:
    image: redis:5.0
    command: redis-server --requirepass mongs123
    ports:
      - 6379:6379
    environment:
      - TZ="Asia/Shanghai"
    volumes:
      - type: volume
        source: redis
        target: /data

volumes:
  redis: 
